### ISSUE TITLE
[Bug] Unknown error (Parser's)

### ISSUE THREAD

**Issue by As1Wills** [Creckeryop/NOBORU#102]
Whenever I try to open a manga it says unknown error (Parser's) I need help

**Comment by Creckeryop** [comment]
What's catalog you were using?
MangaHub isn't working now, and i really can't fix it

**Comment by YawarPandar** [comment]
Hello. I got the same error message when importing some CBZ files. I tried extracting the jpg files and pack them again in a new zip and change de extensions, and same message appears when trying to import again.

**Comment by Creckeryop** [comment]
> Hello. I got the same error message when importing some CBZ files. I tried extracting the jpg files and pack them again in a new zip and change de extensions, and same message appears when trying to import again.

can you send me your cbz file please?

**Comment by YawarPandar** [comment]
Nevermind. I used Kindle Comic Converter to "convert" it to a new CBZ and now it works. Although all files had JPG extension, I guess some of them were not supported, The conversion with KCC corrected this. Thank you anyway. :)
