### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by jcnvfgb** [Creckeryop/NOBORU#109]
Hello. My error is with parsers. [NOBORU-parsers] (https://github.com/Creckeryop/NOBORU-parsers/blob/master/parsers/%5BRU%5DDesu.lua)

1. Go to catalogs
2. Click on "Desu"
3. Click on the manga (any)

I was expecting the manga to open, but the error "unknow error (Parser's)" comes out. According to my observations, in this catalog this error occurs when trying to open any manga.
![2021-12-28-041337](https://user-images.githubusercontent.com/50315748/147518333-76743cd5-0c15-4cf1-a709-5eefd618c123.jpg)

**Comment by jcnvfgb** [comment]
> Hello. My error is with parsers. [NOBORU-parsers] (https://github.com/Creckeryop/NOBORU-parsers/blob/master/parsers/%5BRU%5DDesu.lua)
> 
> Steps to reproduce the behavior:
> 
> 1. Go to catalogs
> 2. Click on "Desu"
> 3. Click on the manga (any)
> 4. Click on any chapter
> 5. See error
> 
> I was expecting the manga to open, but the error "unknow error (Parser's)" comes out. According to my observations, in this catalog this error occurs when trying to open any manga. ![2021-12-28-041337](https://user-images.githubusercontent.com/50315748/147518333-76743cd5-0c15-4cf1-a709-5eefd618c123.jpg)

**Comment by Creckeryop** [comment]
Fixed in 56d65ec226f0897a89b9599bde495e8de9f7543d

**Comment by Creckeryop** [comment]
Fixed in https://github.com/Creckeryop/NOBORU-parsers/commit/56d65ec226f0897a89b9599bde495e8de9f7543d

**Comment by jcnvfgb** [comment]
Thank you. It works now
