### ISSUE TITLE
[Bug] an error occurred

### ISSUE THREAD

**Issue by dnbass89** [Creckeryop/NOBORU#114]
Upon opening noboru after 5 seconds it crashes and gives me this page.
![PXL_20220227_131859603 MP](https://user-images.githubusercontent.com/68236079/155884095-0c94c0e1-4fcc-4fbc-b648-a9be16c786b5.jpg)

Have tried restarting to no avail.

**Comment by Creckeryop** [comment]
What is the version of noboru?

**Comment by dnbass89** [comment]
So reinstalled with the latest version you just pushed and it's working thanks!

**Comment by Creckeryop** [comment]
No problem
