### ISSUE TITLE
Feature request: reading mode top to bottom 

### ISSUE THREAD

**Issue by Ellimosudja** [Creckeryop/NOBORU#12]
Hello, thank you for your app! Verry usefull!

Could you add a way to read chapter in one page from top to bottom in horizontal and vertical mode? like on some website. It would require caching multiple page at once like you wrote in your todo. 

Also navigating with one hand is difficult using sholders buttons, it would solve the problem by allowing to use only up and down.

edit: my bad i missread changing to caching, but it doesn't change my request right?

**Comment by Creckeryop** [comment]
i can't understand what caching multiple page at once is, i've never said that i will add that thing

**Comment by Creckeryop** [comment]
could you please describe your view of controls
left right - is paging left right in horizontal mode
up down - is paging left right in vertical mode
Where i should put moving page left right up down to make app more convenient?

**Comment by Ellimosudja** [comment]
What do you mean by paging?

I'll resume how I can change pages currently (when reading): you can use your fingers to slide to the next page or you can use L/R buttons to go to the previous or the next page, but you can't use left or right with the d-pad or the joystick (because it is used when zooming to navigate?)

Maybe you could had a way to use joystick to move while zoomed and d-pad left or right to change page or the other way, in one long "roll" you'd have only to go up and down to change page.

Also using L/R to go up or down in the menu feel strange to me, using the d-pad or the joystick would be better.

one other thing, in the chapter page there is no way too select continue or read other than touching the green button.

Sorry if i am hard to read or to understand english is not my first language. I can try to explain more if you don't understand what i am talking about.

**Comment by Creckeryop** [comment]
green button is select button

**Comment by Creckeryop** [comment]
I think that the controls should be same for all pages long, short

**Comment by Ellimosudja** [comment]
> I think that the controls should be same for all pages long, short

I don't understand what you are saying

**Comment by Creckeryop** [comment]
okay, i recommend using touch to read manga, i think i will do something with button controls later

**Comment by Ellimosudja** [comment]
Ok, and about the reading mode?

**Comment by Creckeryop** [comment]
to add new reading mode (up to down) i need to rewrite a lot, idk will it be easy or not, i will try

**Comment by Ellimosudja** [comment]
Hello, thank you for adding top to bottom mode! is it possible to load more pages at once? like 5-10 or all chapter so that you don't have to change page and just go down because currently it looks like it's just the way you go to the next page who changed, thanks again.

**Comment by Creckeryop** [comment]
It's not possible without rewriting whole app, and i don't think i will do that, sorry for that.

**Comment by Creckeryop** [comment]
do you think vita can download 5-10 pages at once faster than 5-10 pages consistently?
