### ISSUE TITLE
how do i find where saved comics and "save image" images get saved to?

### ISSUE THREAD

**Issue by roobdog293000** [Creckeryop/NOBORU#128]
when you save an panel from a comic/manga, i have no idea where they appear, not in app files, at least that i can find

**Comment by Creckeryop** [comment]
When you are using "download chapter" feature, all images are located in `/data/noboru/chapters/CHAPTER_KEY_NAME/`. The problem is they are `.image` format, you can rename it by yourself to JPEG, PNG, BMP, GIF formats.

Reason of loss of the format is junk structure of app, that really hard to fix.
