### ISSUE TITLE
VS Code Question

### ISSUE THREAD

**Issue by nolberto82** [Creckeryop/NOBORU#16]
Hello. Did you an extension for this app if so what extension are you using?

**Comment by Creckeryop** [comment]
There is only 3 lua extension i am using
* https://github.com/sumneko/vscode-lua
* https://github.com/keyring/vsc-lua.git
* https://github.com/gccfeli/vscode-lua
other extesions are themes and else
You can find them just by using search "lua" in vs code

**Comment by nolberto82** [comment]
Oh thank you very much.

**Comment by nolberto82** [comment]
Can you run code on your vita through vs code?
By the way I couldn't find vsc-lua does it go by another name?

**Comment by Creckeryop** [comment]
I don't know, I copied links from vscode

**Comment by Creckeryop** [comment]
@nolberto82 no, I just copying new .vpk to vita through ftp, I know that there is a way to just copying changed files, but I'm to lazy for that

**Comment by Creckeryop** [comment]
![image](https://user-images.githubusercontent.com/25725992/75332609-82c53880-58a6-11ea-9a25-c400cebb2900.png)
all called "lua"

**Comment by nolberto82** [comment]
Okay thanks
