### ISSUE TITLE
Problems with PNG images (small scale + repeat)

### ISSUE THREAD

**Issue by konsenss** [Creckeryop/NOBORU#17]
when loading a large number of chapters of some works, for example, solo leveling - the chapters cease to load into the cache, the application cannot open pages starting from chapter 70, they either do not load at all, or break off in half, or appear on a reduced scale, duplicated 3 times - when you try to increase it is seen that the quality is much worse than the same page opened through a computer.

**Comment by Creckeryop** [comment]
what parser you were using?

**Comment by Creckeryop** [comment]
i don't think that there is connection bettween caching and this problem, i want also know other manga that have this problem

**Comment by konsenss** [comment]
I’m sorry, I’m not a fairly advanced user who also does not speak English - which means PARSER in the context of this program.
if about the catalog - desu and mintmanga

**Comment by Creckeryop** [comment]
Хорошо, я проверю

**Comment by konsenss** [comment]
О как, с Уфы. Просто было загружено 90 глав, начиная с 60 - долго грузится. В итоге выхожу к списку глав, жду когда прогрузится превью - открывается без проблем, дальше на середине главы может пропадать изображение и грузиться как будто через интернет, хотя она загружена. Просил проверить на форуме 4пда, сказали что такая же проблема - тут либо программа не справляется, либо сама манхва такая.

**Comment by Creckeryop** [comment]
причем тут 4пда? в каком каталоге ты скачивал Solo Leveling?

**Comment by konsenss** [comment]
Desu.me

**Comment by Creckeryop** [comment]
Может казаться что она загружается из интернета, но это не совсем так, возможно у тебя одновременно скачивается какая-то глава, и так как я не могу нормально разпоточить всё это, у тебя скачивается изображение для скачивающейся главы а потом изображение которое ты читаешь уже с карты памяти. у 70ой главы есть проблема, она не скачивается нормально, потому что там есть GIF изображение, которое не поддерживается моим приложением. Если же какая то загрузка у тебя не отменяется нормально, единственное что я могу посоветовать это перезапустить приложение (я надеюсь что исправлю это в будущем). Также мне интересно узнать про ту страницу которая имеет хуже качество, чем на компе

**Comment by konsenss** [comment]
Чуть позже посмотрю, вроде это были 66-67-68-69, показывало узкую полосу слева, при увеличении ничего нельзя было разобрать, при проматывании вниз появлялся тот же фрагмент немного увеличенный, и третий раз в половину от оригинального размера с худшим качеством

**Comment by konsenss** [comment]
Хотя возможно криво закачались - я не пробовал скачать заново, читал как было

**Comment by Creckeryop** [comment]
Извини пожалуйста за причиненные неудобства

**Comment by Creckeryop** [comment]
Я понимаю что все каталоги я писал, но я советую пользоваться ReadManga MintManga SelfManga для прочтения манги, Desu очень долго скачивает, и у меня не было достаточно времени на проверку каждой манги. Solo Leveling есть в ReadManga и там очень быстро скачивает. Nude Moon может не работать из-за блокировки на территории РФ.

**Comment by konsenss** [comment]
Не нужно извиняться, я в любом случае испытываю удовольствие от использования noboru на покрытой пылью приставке - для меня это гораздо удобней чтения на пк - поэтому в любом случае спасибо! 
В фоне ничего не качалось. Тома грузил дома через вай-фай, читал на работе без интернета. Просто когда начались проблемы с чтением при возврате к выбору глав - серое изображение. Если в этот момент пытаться открыть любую другую главу - ничего не происходит даже через 2 минуты. Если дождаться когда появится превью (секунд 7) - то можно открыть. 67-68 глав проверил - не они, уже 7 минут пытаюсь открыть главы 77-78, загрузка страницы на белом фоне. Интернет 100мбит. Отпишусь как хоть что-то увижу на приставке

**Comment by konsenss** [comment]
Попробую readmanga, спасибо за совет

**Comment by konsenss** [comment]
В общем на desu том 1 глава 43 с первой же страницы все уменьшенное

**Comment by konsenss** [comment]
![IMG_20200325_193942059](https://user-images.githubusercontent.com/62652512/77548516-78f81a80-6ed0-11ea-9719-744730dbc3ed.jpg)
![IMG_20200325_193935245](https://user-images.githubusercontent.com/62652512/77548520-7ac1de00-6ed0-11ea-97c6-9e9e22edce2e.jpg)

**Comment by konsenss** [comment]
На readmanga данной проблемы нет - спасибо огромное! Так бы и сидел на предыдущем каталоге. Тут есть какая-то система поощрений или донатов на пряники?

**Comment by Creckeryop** [comment]
Максимум Звезду тут и тут
https://github.com/Creckeryop/NOBORU
https://github.com/Creckeryop/NOBORU-parsers
Всё сделано не так уж хорошо чтобы донаты за это получать, ну по моему мнению, спасибо за нахождение бага с изображением, попробую его хотя-бы исправить потому что это реальная проблема
