### ISSUE TITLE
Problem with catalog

### ISSUE THREAD

**Issue by phumzster** [Creckeryop/NOBORU#27]
I am only getting 4 options on catalog and 2 of them are raw and the other to domnt have a collection of anime manga. What did i do wrong? Help me.

**Comment by Creckeryop** [comment]
I can't understand

**Comment by phumzster** [comment]
I meant to say the sources I can't get other websites. Why is that ?

**Comment by Creckeryop** [comment]
okay, i think there is solutions:
* Check preferred language in catalogs settings, try set to different
* Press Refresh in Catalogs and wait for a 30 seconds (there is a chance that they aren't loading at all make screenshot of console (START+DPAD_LEFT))
* If that doesn't help try reset all settings from Data Settings

Write here again if that doesn't helped
