### ISSUE TITLE
[Feature Request] MangaDex authentication

### ISSUE THREAD

**Issue by bb010g** [Creckeryop/NOBORU#28]
It'd be nice to use a MangaDex account to access search in-app (beyond ID lookups).

Tachiyomi handles this by sharing cookies with a browser session, but I'm not sure if you can yank cookies like that easily from the Vita's Browser.

**Comment by Creckeryop** [comment]
Tried to make it, Got cookies from browser, but they aren't fits to my app((( don't know why

**Comment by Creckeryop** [comment]
I think i found why that happens :DDDD

**Comment by Creckeryop** [comment]
In short, this feature works bad, here's possible reasons:
* browser have cookie problems (they are deleting sometimes)
* my code isn't good

**Comment by Creckeryop** [comment]
You can make sure that browser have cookie problems by login to mangadex and update page to check login

**Comment by bb010g** [comment]
Could you store the auth cookies for sites like MangaDex locally in Noboru after import?

**Comment by Creckeryop** [comment]
cookies expires at the next day you saved it

**Comment by Creckeryop** [comment]
Check this https://twitter.com/trash_cookie/status/1254459045748105218

**Comment by bb010g** [comment]
You didn't check "Remember me (1 year)"?

**Comment by Creckeryop** [comment]
> Could you store the auth cookies for sites like MangaDex locally in Noboru after import?

So i should save my cookies for all users? or what do you mean

**Comment by bb010g** [comment]
Sorry, just gave the `cookies` branch code another read, and I think I get what's going on now. Disregard that comment. I'm assuming the code for general integration (or just MangaDex-specific, but generally reusing browser cookies on requests makes more sense to me) of cookies into search & other requests hasn't been publicly pushed yet?

I have to wonder if account support might help with rate limiting problems when downloading lots of chapters currently (without authentication).

**Comment by Creckeryop** [comment]
i can't understand what are tou speaking about

**Comment by Creckeryop** [comment]
i'll better close this request, because i already done this in 2fd900ae70b8e15f610b89c375ef74ec780d45f7
