### ISSUE TITLE
Having trouble downloading from mangahub.io.

### ISSUE THREAD

**Issue by nanashi89** [Creckeryop/NOBORU#34]
It starts at 0%, then says there's a problem with the connection.

readcomicsonline.ru behaves itself very nicely, so it couldn't be the connection...

Have the latest version of noboru, BTW.

**Comment by Creckeryop** [comment]
Are you sure that mangahub.io works? Have you tried to go there from browser?

**Comment by Creckeryop** [comment]
If it's server problem, why you write to me, and why you write here? All parsers problems should be in Parsers repository, if error related to one parser you better write in parser repo, if all parsers don't work, you should write here

**Comment by Creckeryop** [comment]
In short: It's working. First of all, before you write a issue, be sure that problem isn't MangaHub's, how to check that? You should go to MangaHub from your computer, if it is not loading or takes long time, it's not NOBORU problem. Also, there is a text in description, have you seen it?
![image](https://user-images.githubusercontent.com/25725992/80301401-59009300-87bd-11ea-8c9a-50fd050ea7c3.png)
If problem happens with one parser you should write your issue [HERE](https://github.com/Creckeryop/NOBORU-parsers)
If problem happens with all catalogs ofc, maybe it's not a parsers problem, so you should write in NOBORU repo
