### ISSUE TITLE
Net Problem/New Parsers Solicitation

### ISSUE THREAD

**Issue by DiegooBedin** [Creckeryop/NOBORU#37]
I talked to you Crekeryop on Reddit and informed you that the website "ninemangabr" was having problems with Ecchi manga because the website asked for age authentication, and you fixed it and it was perfect. But at 0.51 att, this problem occurred again. But now, all the manga on the site "http://br.ninemanga.com" is in trouble and does not load the chapters and not just the manga with old authentication. We are also unable to see the website catalog. I know this is because I have some saved in my library.

Maybe if you could solve this problem or add other sites ... It would be nice to have new parsers in Portuguese/brazilian.

In addition to this problem with "ninemanga br", it seems that other sites also do not work, here for example, I was unable to open any more manga in any parser.

**Comment by Creckeryop** [comment]
Why you writting here? not in [HERE](https://github.com/Creckeryop/NOBORU-parsers)?
![image](https://user-images.githubusercontent.com/25725992/80442159-d0513680-8925-11ea-907b-ca5073c38365.png)

**Comment by Creckeryop** [comment]
Tryied to fix, check it

**Comment by Creckeryop** [comment]
About adding other parsers, look at this, i just can't open them
![image](https://user-images.githubusercontent.com/25725992/80444387-18bf2300-892b-11ea-9559-ae1372cf559b.png)
![image](https://user-images.githubusercontent.com/25725992/80444400-21aff480-892b-11ea-820c-79947f82cc56.png)
![image](https://user-images.githubusercontent.com/25725992/80444420-2b395c80-892b-11ea-94b1-84e1c14ee5f5.png)
![image](https://user-images.githubusercontent.com/25725992/80444436-31c7d400-892b-11ea-84ca-68bf092eadc1.png)

**Comment by Creckeryop** [comment]
even with proxy, these sites don't work

**Comment by DiegooBedin** [comment]
You said in another answer that if the problem was of the catalog it could be opened here ..


> Tentou consertar, verifique
This is wonderful again, everything is ok now, thanks man

**Comment by DiegooBedin** [comment]
You said in another answer that if the problem was of the catalog it could be opened here ..


> Tryied to fix, check it

This is wonderful again, everything is ok now, thanks man

**Comment by Creckeryop** [comment]
![image](https://user-images.githubusercontent.com/25725992/80514430-edbfe800-8999-11ea-977f-e93bd4482451.png)
"HERE" is a link i will edit special for you

**Comment by DiegooBedin** [comment]
> even with proxy, these sites don't work for me

this is strange, here everyone is working perfectly for me

"https://mangalivre.net/#"
"https://mangahost.site/"
"https://mangayabu.com/"
"https://leitor.net/"
"http://centraldemangas.online/"

All of these that I informed you to add anyone are working perfectly here

**Comment by DiegooBedin** [comment]
> ![image](https://user-images.githubusercontent.com/25725992/80514430-edbfe800-8999-11ea-977f-e93bd4482451.png)
> "HERE" is a link i will edit special for you

Sorry, I don't want to cause you any problems. That was the answer I saw, so I opened the issue here.

So, you answered me here, can I stay here or do you want me to open a request there?

**Comment by Creckeryop** [comment]
im glad that they are perfectly works for you, that's very nice, BUT, if they aren't accessible for me even with VPN (because servers just dont gives access to other countries), what should i do, i can't even see how it looks? Also i said already that i can't add sites with captcha. I do want to add more parser for all you guys, but i already said, that sites don't work, and i can't do anything with this, 
http://centraldemangas.online/ looks that this site only works but here's problem:
* there is no Ranking pages (only top10, that doesn't count)
* i can only add A-Z mode and add Search from this site, 

and please don't write here with parsers, This is repo only for App problems (Parsers problems isn't related to this app, *parser is another program, and errors with parsers is error with another program not with app*, that's why i just angry about that)

**Comment by DiegooBedin** [comment]
I understand that you need to see how it looks, and I'm sorry that you can't see it, but any option that you can add Portuguese / Brazilian will be great, and I'm sure that not only me, but many others, we will be grateful. I thought of giving these 5 options, because I use one of them when I read manga to find what I want (the one that doesn't have a website, but has another website), but the websites that I use may not be the choice of everyone who reads manga in Portuguese, that's why I showed you these 5 sites. If you manage to add, we will be grateful.

I am passionate about manga of various genres, I always see the manga before the anime, so when I saw your vpk for vita, I was very happy. So, for me, it's a great vpk, and I think your work is fantastic, I just have to thank you.


I apologize again for this error. I will not comment here, any other comment, tip or website about analyzers that I will do there.
