### ISSUE TITLE
Add Mangasee in the catalog 

### ISSUE THREAD

**Issue by Retr0-15** [Creckeryop/NOBORU#39]
Just wanna request for you to add the Mangasee beacause it has a wide variety of HQ english manga.

**Comment by Creckeryop** [comment]
Are you all trolling me? that's repository not for catalog request, all catalog requests should be in https://github.com/Creckeryop/NOBORU-parsers repo

**Comment by Creckeryop** [comment]
Added MangaSee, so you can refresh catalogs list from app

**Comment by Retr0-15** [comment]
I'm sorry about that didn't read carefully. 😅
Btw. Thank you! 😊
