### ISSUE TITLE
Problema con i downloads !!

### ISSUE THREAD

**Issue by PeppeLaw97** [Creckeryop/NOBORU#52]
Salve a tutti, ho una domanda.
Perché quando scarico un capitolo, dopo il completamento non lo trovo nella sezione "Donwloads" ?? . Mi spiego meglio, se provo a scaricare un capitolo, mi esce nella sezione dei download con la barra di completamento, ma una volta finito non so come visualizzarlo senza connessione, perché traccia del capitolo scaricato non c'è in nessuna sezione del menù... Andando nella cartella "ux0:data/noboru/chapters/"  trovo la cartella scaricata ma con all'interno i file delle scan con estensione ".image". Per visualizzarli devo rinominare ogni singolo file in uno dei formati supportato e solo così posso usufruirne, ma è una cosa scomodissima... Ho provato anche a spostare la cartella nella directory "ux0:data/noboru/import/" ma le scan lo stesso non mi vengono visualizzate, almeno che non rinomino ogni singolo file.
Devo cambiare qualcosa nelle impostazioni ?? 
Qualcuno mi sa essere d'aiuto ?? 
GRAZIE IN ANTICIPO.

**Comment by Creckeryop** [comment]
The “**Download**” section is made only for a download queue, so all downloaded chapters shouldn’t appear there. All downloaded chapters are available from the **manga** section (where you can see a list of chapters) not to lose manga I recommend pressing the “add to library” button (and also enabling **Settings**->**Catalogs**->**Show only downloaded chapters in offline mode** or **IMPOSTAZIONI**->**Cataloghi**->**Mostra solo i capitoli scaricati offline**). To make sure that a chapter is downloaded you can check the icon in front of a chapter’s name:
* The Cross icon means that a manga is downloaded, pressing that button will delete the chapter from memory
* The Percentage means that a manga is downloading or in a queue, pressing that button will cancel the chapter downloading
* The Download icon means that a manga isn’t downloaded, pressing that button will put download in a queue

If you see that there is the cross icon in front of a chapter’s name, it means that you can start reading this chapter from a memory without internet connection.

![image](https://user-images.githubusercontent.com/25725992/83948568-89fdca00-a837-11ea-9081-1b7227e6806a.png)

**Comment by Bek72** [comment]
У меня есть вопрос,как можно выбрать жанр манги?Ну я знаю что при нажатии квадрата то открывается меню.Я выбераю жанр но при закрытии ничего не происходит.Еще вопрос,зачем панель открывающаяся на треугольник?Добавьте мануал или описание.А приложение супер.Лучшее что нашёл.

**Comment by Creckeryop** [comment]
Надо после выбора жанра нажать поиск и ввести название либо просто нажать ок
