### ISSUE TITLE
[FEATURE REQUEST]Add uma0 support 

### ISSUE THREAD

**Issue by AceCuba** [Creckeryop/NOBORU#55]
This will be awesome . Store comic's on the uma0 of the psvita tv or a mc card on a psvita Mount like uma0 and sd2vita in ux0 like me.

**Comment by Creckeryop** [comment]
To add this feature, i need sony card

**Comment by AceCuba** [comment]
Sad ypu gpt a psvita fat ? . If you have a psvita slim you can mount the internal memory in uma0: . The idea of this is many people have a sd2vita for games and a mc Mount in uma for emulators (adrenaline,deaelux) ,music,movies. Will be awesome to have a uma full of comic's

**Comment by AceCuba** [comment]
Your app it's really awesome sorry if i asking too much .

**Comment by AceCuba** [comment]
Mmm and you can live the internal stuff of the app like cache and stuff in ux0 . But downloads and imported comics on uma . I dont know , i will be very happy to see this implement and the people with psvita tv .

**Comment by Creckeryop** [comment]
> Sad ypu gpt a psvita fat ? . If you have a psvita slim you can mount the internal memory in uma0: . The idea of this is many people have a sd2vita for games and a mc Mount in uma for emulators (adrenaline,deaelux) ,music,movies. Will be awesome to have a uma full of comic's

my psvita is fat, and i gifted my sony card to friend with 3.66+ ps vita (hack on 3.66+ requires sony card on fat models).

**Comment by Creckeryop** [comment]
I'll try to come up with something

**Comment by AceCuba** [comment]
> > Sad ypu gpt a psvita fat ? . If you have a psvita slim you can mount the internal memory in uma0: . The idea of this is many people have a sd2vita for games and a mc Mount in uma for emulators (adrenaline,deaelux) ,music,movies. Will be awesome to have a uma full of comic's
> 
> my psvita is fat, and i gifted my sony card to the friend with 3.66+ ps vita (hack on 3.66+ requires sony card on fat models).

Bro tell your friend to downgrade to 3.65 its possible . I downgrade mine fat 3.73-3.65 and enso work nice spoff anf osiscall for the games

**Comment by AceCuba** [comment]
> I'll try to come up with something

Again you work it's awesome . I live in cuba and dont have access to any tipe of banc transfer or PayPal , you really deserve a donation jajaa.keep the good work

**Comment by Creckeryop** [comment]
i don't take any donations
