### ISSUE TITLE
[Feature Request] add mangapark source

### ISSUE THREAD

**Issue by Naoki288000** [Creckeryop/NOBORU#58]

**Comment by Creckeryop** [comment]
You haven't read that you shouldn't write here this thing?

**Comment by Naoki288000** [comment]
> You haven't read that you shouldn't write here this thing?



> You haven't read that you shouldn't write here this thing?

No, sorry. I'm kinda new here. Where should i post it?

**Comment by Creckeryop** [comment]
https://github.com/Creckeryop/NOBORU-parsers/issues

**Comment by Creckeryop** [comment]
i can't add mangapark by the way (site uses captcha)

**Comment by Naoki288000** [comment]
> i can't add mangapark by the way (site uses captcha)

I see... thank you for the reply
