### ISSUE TITLE
[Bug] Page break in menu

### ISSUE THREAD

**Issue by eze92** [Creckeryop/NOBORU#66]
Could you indicate in the menu the number of pages below that can be skipped / scrolled? since if one tries to use this option and is given a number greater than the available one, sometimes the application tends to fail

**Comment by Creckeryop** [comment]
To do that, i need to change all available catalogs.
Could you tell me what catalog you were using that leads app to fail?

**Comment by eze92** [comment]
Sorry I did not answer I had misplaced and forgotten, I only use the links to pages in Spanish but lately I did not throw the error again the last times I tried

**Comment by Creckeryop** [comment]
I think this is memory leak error, that i hope will be fixed soon
