### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xxfraser** [Creckeryop/NOBORU#83]
Their is a problem with one of noboru catalogs page (MangaHub) it opens and everything loads fine but when you click on a manga to read it loads endlessly forever and doesn’t load the page to see the manga. I tried reinstalling and wife reset nothing works but the others catalog pages loads fine.

**Comment by xxfraser** [comment]
I just made an account to tell you this.

**Comment by Creckeryop** [comment]
I don't know, i don't have any problems with it
Try to go mangahub.io on your browser, maybe it's not app problem. Also, what's name of manga and chapter, that is not loading?

**Comment by xxfraser** [comment]
If fixed now I just give up and waited a day to see what happen all the manga pages load now at first none would even load to the manga page
