### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xxfraser** [Creckeryop/NOBORU#97]
This bug happen yesterday night I waited a day to see what will happen and it’s still there
 
When I go to MangaHub and go to click on a manga to read it attempts to load and then closes me out of the manga I wanted to read and at the bottom it says  (Unknown error Parsers)
![image](https://user-images.githubusercontent.com/78988991/113453100-b6449180-93db-11eb-9ab4-7aba538268c9.jpg)

**Comment by xxfraser** [comment]
It happen to all the manga so I can’t read anything in Mangahub the other catalog seem to work sometimes

**Comment by Creckeryop** [comment]
Refresh catalog list

**Comment by Creckeryop** [comment]
It's not a bug, mangaHub changed their API access

**Comment by xxfraser** [comment]
I ok I try

**Comment by xxfraser** [comment]
Still does not work for me it still says unknown error and I refreshed the catalog so weird @Creckeryop

**Comment by xxfraser** [comment]
![image](https://user-images.githubusercontent.com/78988991/113454775-6a93e700-93df-11eb-8da3-3e1a36556096.jpg)

**Comment by Creckeryop** [comment]
Okay i undestand now, MangaHub changed their API, so now you can't just make POST request to their API, you need to somehow get access for it. I really don't have any ideas how to fix it. MangaHub parser now can't work with web manga. I really recommend to move on other source, or advice me new source i will try to make parser for it. Sorry about that 😢

**Comment by xxfraser** [comment]
It’s ok I re download noboru and some of the manga works but not all I’ll trt to move on to another source cuz 90% of the manga I read are from there thank you for trying to help
