### ISSUE TITLE
Unknown Error (Parser's)

### ISSUE THREAD

**Issue by wanhitcombo** [Creckeryop/NOBORU#98]
![2021-04-21-171038](https://user-images.githubusercontent.com/43747891/115529921-e5a53a80-a2c5-11eb-8661-ec8df1d07c96.jpg)

This manga is from the library, not an imported one

**Comment by Creckeryop** [comment]
https://github.com/Creckeryop/NOBORU/issues/97

**Comment by Creckeryop** [comment]
For today Noboru doesn't support api of mangahub, because they turned on javascript check on their API
![image](https://user-images.githubusercontent.com/25725992/115648481-ef1eb900-a33e-11eb-9028-75f89cd8442a.png)
